name: Auto /signin

on:
  # 定时触发 - 每70分钟执行一次
  schedule:
    - cron: '*/61 * * * *'
  
  # 手动触发
  workflow_dispatch:

jobs:
  signin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: setup Node.js 25
      uses: actions/setup-node@v4
      with:
        node-version: '25'

    - name: Run signin.js
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        node signin.js
