name: Auto /signin

on:
  # 定时触发 - 每72分钟执行一次（每天执行20次）
  schedule:
    # 0:00
    - cron: '0 0 * * *'
    # 1:12
    - cron: '12 1 * * *'
    # 2:24
    - cron: '24 2 * * *'
    # 3:36
    - cron: '36 3 * * *'
    # 4:48
    - cron: '48 4 * * *'
    # 6:00
    - cron: '0 6 * * *'
    # 7:12
    - cron: '12 7 * * *'
    # 8:24
    - cron: '24 8 * * *'
    # 9:36
    - cron: '36 9 * * *'
    # 10:48
    - cron: '48 10 * * *'
    # 12:00
    - cron: '0 12 * * *'
    # 13:12
    - cron: '12 13 * * *'
    # 14:24
    - cron: '24 14 * * *'
    # 15:36
    - cron: '36 15 * * *'
    # 16:48
    - cron: '48 16 * * *'
    # 18:00
    - cron: '0 18 * * *'
    # 19:12
    - cron: '12 19 * * *'
    # 20:24
    - cron: '24 20 * * *'
    # 21:36
    - cron: '36 21 * * *'
    # 22:48
    - cron: '48 22 * * *'

  # 手动触发
  workflow_dispatch:

jobs:
  signin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: setup Node.js 25
      uses: actions/setup-node@v4
      with:
        node-version: '25'

    - name: Run signin.js
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        node signin.js