name: Auto /signin

on:
  # 定时触发 - 每62分钟执行一次
  schedule:
    # 1:02
    - cron: '2 1 * * *'
    # 2:04
    - cron: '4 2 * * *'
    # 3:06
    - cron: '6 3 * * *'
    # 4:08
    - cron: '8 4 * * *'
    # 5:10
    - cron: '10 5 * * *'
    # 6:12
    - cron: '12 6 * * *'
    # 7:14
    - cron: '14 7 * * *'
    # 8:16
    - cron: '16 8 * * *'
    # 9:18
    - cron: '18 9 * * *'
    # 10:20
    - cron: '20 10 * * *'
    # 11:22
    - cron: '22 11 * * *'
    # 12:24
    - cron: '24 12 * * *'
    # 13:26
    - cron: '26 13 * * *'
    # 14:28
    - cron: '28 14 * * *'
    # 15:30
    - cron: '30 15 * * *'
    # 16:32
    - cron: '32 16 * * *'
    # 17:34
    - cron: '34 17 * * *'
    # 18:36
    - cron: '36 18 * * *'
    # 19:38
    - cron: '38 19 * * *'
    # 20:40
    - cron: '40 20 * * *'
    # 21:42
    - cron: '42 21 * * *'
    # 22:44
    - cron: '44 22 * * *'
    # 23:46
    - cron: '46 23 * * *'
  
  # 手动触发
  workflow_dispatch:

jobs:
  signin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: setup Node.js 25
      uses: actions/setup-node@v4
      with:
        node-version: '25'

    - name: Run signin.js
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        node signin.js